CC=gcc
AR=ar
OBJECTS_MAIN=main.o
OBJECTS_LIB=StrList.o
FLAGS= -Wall -g

all: StrList 

StrList: $(OBJECTS_MAIN) $(OBJECTS_LIB) 
	$(CC) -o  StrList StrList.o main.o
		
StrList.o: StrList.c StrList.h
	$(CC) $(FLAGS) -c StrList.c

main.o: main.c StrList.h
	$(CC) $(FLAGS) -c main.c

clean:
	rm -f *.o *.a *.so StrList